# Generated by Django 6.0.3 on 2026-03-20 21:53

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('account_type', models.CharField(choices=[('Bot', 'Bot'), ('Organization', 'Organization'), ('User', 'User')], default='User', max_length=20)),
                ('discovery_method', models.CharField(choices=[('Collaborator', 'Collaborator'), ('Contributor', 'Contributor'), ('Follower', 'Follower'), ('Following', 'Following'), ('OrgMember', 'OrgMember'), ('Search', 'Search')], default='Search', max_length=20)),
                ('status', models.CharField(choices=[('Unknown', 'Unknown'), ('Confirmed', 'Confirmed'), ('Hidden', 'Hidden')], default='Unknown', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=4096, null=True)),
                ('location', models.CharField(blank=True, max_length=4096, null=True)),
                ('url', models.URLField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_user_id', models.BigIntegerField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('origin', models.CharField(choices=[('GitHub', 'GitHub'), ('GitLab', 'GitLab')], default='GitHub', max_length=20)),
            ],
            options={
                'db_table': 'git_user',
                'indexes': [models.Index(fields=['username'], name='git_user_usernam_6510fc_idx'), models.Index(fields=['source_user_id', 'origin'], name='git_user_source__2fcaae_idx'), models.Index(fields=['status'], name='git_user_status_e9c6aa_idx'), models.Index(fields=['account_type'], name='git_user_account_3bea8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=511)),
                ('source_repo_id', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('default_branch', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('stars', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('is_fork', models.BooleanField(default=False)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('origin', models.CharField(choices=[('GitHub', 'GitHub'), ('GitLab', 'GitLab')], default='GitHub', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='git_data.user')),
            ],
            options={
                'db_table': 'git_repo',
            },
        ),
        migrations.CreateModel(
            name='Gist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gist_id', models.CharField(max_length=255)),
                ('revision_id', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('filenames', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4096), blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('GitHub', 'GitHub'), ('GitLab', 'GitLab')], default='GitHub', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gists', to='git_data.user')),
            ],
            options={
                'db_table': 'git_gist',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('GitHub', 'GitHub'), ('GitLab', 'GitLab')], default='GitHub', max_length=20)),
                ('sha', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('url', models.URLField()),
                ('commit_date', models.DateTimeField(blank=True, null=True)),
                ('branch_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='git_data.repo')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_commits', to='git_data.user')),
                ('committer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committed_commits', to='git_data.user')),
            ],
            options={
                'db_table': 'git_commit',
            },
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Collaborator', 'Collaborator'), ('Contributor', 'Contributor'), ('Following', 'Following'), ('Follower', 'Follower'), ('OrgMember', 'OrgMember')], max_length=20)),
                ('origin', models.CharField(choices=[('GitHub', 'GitHub'), ('GitLab', 'GitLab')], default='GitHub', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='git_data.user')),
                ('repo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='git_data.repo')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='git_data.user')),
            ],
            options={
                'db_table': 'git_user_relationship',
            },
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['full_name'], name='git_repo_full_na_abd571_idx'),
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['source_repo_id', 'origin'], name='git_repo_source__b736b1_idx'),
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['owner'], name='git_repo_owner_i_750a28_idx'),
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['stars'], name='git_repo_stars_f0e561_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repo',
            unique_together={('source_repo_id', 'origin')},
        ),
        migrations.AddIndex(
            model_name='gist',
            index=models.Index(fields=['author'], name='git_gist_author__ede447_idx'),
        ),
        migrations.AddIndex(
            model_name='gist',
            index=models.Index(fields=['source_created_at'], name='git_gist_source__f2bffe_idx'),
        ),
        migrations.AddIndex(
            model_name='gist',
            index=models.Index(fields=['gist_id', 'revision_id'], name='git_gist_gist_id_02cc8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gist',
            unique_together={('gist_id', 'revision_id', 'origin')},
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['sha'], name='git_commit_sha_c9ba7b_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['repo', 'author'], name='git_commit_repo_id_4a922a_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_date'], name='git_commit_commit__517f80_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['branch_name'], name='git_commit_branch__52d81c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together={('sha', 'repo')},
        ),
        migrations.AddIndex(
            model_name='userrelationship',
            index=models.Index(fields=['from_user', 'relationship_type'], name='git_user_re_from_us_8fb6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='userrelationship',
            index=models.Index(fields=['to_user', 'relationship_type'], name='git_user_re_to_user_9b1edb_idx'),
        ),
        migrations.AddIndex(
            model_name='userrelationship',
            index=models.Index(fields=['repo'], name='git_user_re_repo_id_6b0ae1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrelationship',
            unique_together={('from_user', 'to_user', 'relationship_type', 'repo')},
        ),
    ]
