# Generated by Django 6.0.3 on 2026-03-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='repo',
            name='git_repo_source__b736b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='git_user_source__2fcaae_idx',
        ),
        migrations.AlterUniqueTogether(
            name='repo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commit',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='origin',
        ),
        migrations.AlterUniqueTogether(
            name='gist',
            unique_together={('gist_id', 'revision_id')},
        ),
        migrations.RemoveField(
            model_name='userrelationship',
            name='origin',
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['source_repo_id'], name='git_repo_source__5c4a36_idx'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='gist',
            name='origin',
        ),
    ]
