# Generated by Django 6.0.3 on 2026-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0002_remove_repo_git_repo_source__b736b1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='from_event',
            field=models.BooleanField(default=False),
        ),
    ]
