# Generated by Django 6.0.3 on 2026-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0003_commit_from_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='latest_event_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
