# Generated by Django 6.0.3 on 2026-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0004_repo_latest_event_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='is_fork',
            field=models.BooleanField(default=False),
        ),
    ]
