# Generated by Django 6.0.3 on 2026-05-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0005_gist_is_fork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
