# Generated by Django 6.0.3 on 2026-05-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0006_user_email_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
