# Generated by Django 6.0.3 on 2026-06-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0007_user_scanned_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['processed_at'], name='git_commit_process_edf3f6_idx'),
        ),
    ]
