# Generated by Django 6.0.3 on 2026-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0008_add_commit_processed_at_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gist',
            index=models.Index(fields=['processed_at'], name='git_gist_process_eaabaf_idx'),
        ),
        migrations.AddIndex(
            model_name='repo',
            index=models.Index(fields=['processed_at'], name='git_repo_process_c2fd84_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['processed_at'], name='git_user_process_3a0f56_idx'),
        ),
    ]
