# Generated by Django 6.0.3 on 2026-03-20 21:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_path', models.CharField(db_index=True, max_length=255)),
                ('queue_name', models.CharField(db_index=True, default='default', max_length=100)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('run_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('SUCCESSFUL', 'Successful')], db_index=True, default='READY', max_length=12)),
                ('enqueued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'enqueued_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=100, unique=True)),
                ('queue_name', models.CharField(db_index=True, default='default', max_length=100)),
                ('hostname', models.CharField(max_length=255)),
                ('pid', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('STARTING', 'Starting'), ('IDLE', 'Idle'), ('RUNNING', 'Running'), ('STOPPING', 'Stopping'), ('STOPPED', 'Stopped'), ('DEAD', 'Dead')], db_index=True, default='STARTING', max_length=16)),
                ('stop_requested', models.BooleanField(default=False)),
                ('heartbeat_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_error', models.TextField(blank=True, default='')),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_workers', to='task_queue.taskjob')),
            ],
            options={
                'ordering': ['worker_name'],
            },
        ),
        migrations.AddField(
            model_name='taskjob',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='task_queue.taskworker'),
        ),
        migrations.AddIndex(
            model_name='taskworker',
            index=models.Index(fields=['queue_name', 'status'], name='task_queue__queue_n_ef6b80_idx'),
        ),
        migrations.AddIndex(
            model_name='taskworker',
            index=models.Index(fields=['heartbeat_at'], name='task_queue__heartbe_cdf4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskjob',
            index=models.Index(fields=['status', 'queue_name', '-priority', 'enqueued_at'], name='task_queue__status_b29ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='taskjob',
            index=models.Index(fields=['queue_name', 'run_after'], name='task_queue__queue_n_d9bdb4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskjob',
            index=models.Index(fields=['status', 'run_after'], name='task_queue__status_d258a3_idx'),
        ),
    ]
