# Generated by Django 6.0.3 on 2026-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworker',
            name='claim_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taskworker',
            name='model_claims',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
