# Generated by Django 6.0.3 on 2026-03-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Descriptive label for this token', max_length=100, unique=True)),
                ('token', models.CharField(help_text='GitHub personal access token', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_github_tokens',
                'ordering': ['-is_active', 'label'],
            },
        ),
    ]
