# Generated by Django 6.0.3 on 2026-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField()),
                ('sha', models.BinaryField(max_length=20)),
                ('observed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'raw_events',
                'indexes': [models.Index(fields=['repo_id'], name='raw_events_repo_id_f52c2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('repo_id', 'sha'), name='uniq_repo_sha')],
            },
        ),
    ]
