# Generated by Django 6.0.3 on 2026-03-20 21:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('git_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Human-readable name for this pattern', max_length=255, null=True)),
                ('regex_pattern', models.TextField(help_text='Regular expression pattern to match')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pattern should be actively matched')),
                ('category', models.CharField(choices=[('Ai tokens', 'Ai tokens'), ('Api and webhooks', 'Api and webhooks'), ('Auth headers', 'Auth headers'), ('Aws infrastructure', 'Aws infrastructure'), ('Cloud keys tokens', 'Cloud keys tokens'), ('Connection strings db', 'Connection strings db'), ('Development tools', 'Development tools'), ('Docker container registry', 'Docker container registry'), ('Hosting platforms', 'Hosting platforms'), ('Jwt tokens', 'Jwt tokens'), ('Messaging communication', 'Messaging communication'), ('Network infrastructure', 'Network infrastructure'), ('Passwords and secrets generic', 'Passwords and secrets generic'), ('Payment financial', 'Payment financial'), ('Pii icelandic', 'Pii icelandic'), ('Private keys', 'Private keys'), ('Social media apis', 'Social media apis'), ('Urls general', 'Urls general'), ('User email pass combos', 'User email pass combos'), ('Usernames', 'Usernames'), ('Uuids', 'Uuids'), ('Other', 'Other')], default='Other', help_text='Category of this pattern', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_regex',
                'indexes': [models.Index(fields=['is_active'], name='search_rege_is_acti_046093_idx'), models.Index(fields=['category'], name='search_rege_categor_a0fbd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('Addition', 'Addition'), ('Deletion', 'Deletion')], help_text='Whether found in addition or deletion', max_length=10)),
                ('match', models.TextField(help_text='The exact matched string')),
                ('raw_match', models.TextField(help_text='The entire line of code containing the match')),
                ('filename', models.CharField(blank=True, help_text='Filename where match was found', max_length=1024)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='git_data.commit')),
                ('gist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='git_data.gist')),
                ('regex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='search.regex')),
            ],
            options={
                'db_table': 'search_match',
                'indexes': [models.Index(fields=['regex'], name='search_matc_regex_i_44209e_idx'), models.Index(fields=['commit'], name='search_matc_commit__7f9f81_idx'), models.Index(fields=['gist'], name='search_matc_gist_id_03f28f_idx'), models.Index(fields=['match_type'], name='search_matc_match_t_67a145_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('commit__isnull', False), ('gist__isnull', False), _connector='OR'), name='match_has_commit_or_gist'), models.CheckConstraint(condition=models.Q(('commit__isnull', False), ('gist__isnull', False), _negated=True), name='match_not_both_commit_and_gist')],
            },
        ),
    ]
