# Generated by Django 6.0.3 on 2026-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0002_remove_repo_git_repo_source__b736b1_idx_and_more'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='regex',
            options={'verbose_name_plural': 'Regexes'},
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('commit__isnull', False)), fields=('regex', 'commit', 'match_type', 'match', 'filename'), name='uniq_commit_match'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('gist__isnull', False)), fields=('regex', 'gist', 'match_type', 'match', 'filename'), name='uniq_gist_match'),
        ),
    ]
