# Generated by Django 6.0.3 on 2026-03-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_match_options_alter_regex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regex',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
