# Generated by Django 6.0.3 on 2026-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_match_filename_alter_match_match_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='regex',
            constraint=models.UniqueConstraint(fields=('regex_pattern',), name='uniq_regex_pattern'),
        ),
    ]
