# Generated by Django 6.0.3 on 2026-05-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0005_gist_is_fork'),
        ('search', '0006_match_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='uniq_commit_match',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='uniq_gist_match',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='search_matc_match_t_67a145_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='search_matc_status_d0ec1d_idx',
            old_name='search_matc_status_idx',
        ),
        migrations.AddField(
            model_name='match',
            name='deleted_in_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_matches', to='git_data.commit'),
        ),
        migrations.AddField(
            model_name='match',
            name='deleted_in_gist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_matches', to='git_data.gist'),
        ),
        migrations.AlterField(
            model_name='regex',
            name='category',
            field=models.CharField(choices=[('Ai tokens', 'Ai tokens'), ('Api and webhooks', 'Api and webhooks'), ('Auth headers', 'Auth headers'), ('Aws infrastructure', 'Aws infrastructure'), ('Cloud keys tokens', 'Cloud keys tokens'), ('Connection strings db', 'Connection strings db'), ('Development tools', 'Development tools'), ('Docker container registry', 'Docker container registry'), ('Hosting platforms', 'Hosting platforms'), ('Jwt tokens', 'Jwt tokens'), ('Messaging communication', 'Messaging communication'), ('Network infrastructure', 'Network infrastructure'), ('Passwords and secrets generic', 'Passwords and secrets generic'), ('Payment financial', 'Payment financial'), ('Private keys', 'Private keys'), ('Social media apis', 'Social media apis'), ('Urls general', 'Urls general'), ('User email pass combos', 'User email pass combos'), ('Usernames', 'Usernames'), ('Uuids', 'Uuids'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['deleted_in_commit'], name='search_matc_deleted_2db33c_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['deleted_in_gist'], name='search_matc_deleted_de5d67_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('commit__isnull', False)), fields=('regex', 'commit', 'match', 'filename'), name='uniq_commit_match'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('gist__isnull', False)), fields=('regex', 'gist', 'match', 'filename'), name='uniq_gist_match'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_type',
        ),
    ]
