# Generated by Django 6.0.3 on 2026-05-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_data', '0005_gist_is_fork'),
        ('search', '0007_match_deleted_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gist_base_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='git_data.repo'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['repo'], name='search_matc_repo_id_97255a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['gist_base_id'], name='search_matc_gist_ba_62670e_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('repo__isnull', False)), fields=('regex', 'repo', 'match'), name='uniq_repo_match'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('gist_base_id__isnull', False)), fields=('regex', 'gist_base_id', 'match'), name='uniq_gist_base_match'),
        ),
    ]
